---
title: "ATACseq"
author: "Tim Stuart"
date: "29/10/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(readr)
library(RColorBrewer)
```

Load data

```{r data}
files <- list.files("../Data/", full.names = TRUE)
dat <- lapply(files, read_tsv)
names(dat) <- list.files("../Data")
```

Define function

```{r}
plot_heatmap <- function(d, chromosome, color, sample_name) {
        subs_data <- d[d$chromosome == chromosome,]
        return(image(as.matrix(subs_data$normalized_coverage),
                     col = color,
                     main = sample_name))
}
```

```{r}
color <- colorRampPalette(brewer.pal(9, "YlGn"))(100)
```

Apply function to list of files

```{r heatmaps}
for(chrom in seq(1, 5)){
        pdf(paste("../Plots/chr", as.character(chrom), ".pdf", sep = ""), height = 40, width = 5)
        par(mfrow=c(20, 1))
        for(i in seq_along(dat)){
                plot_heatmap(dat[[i]], chromosome = as.character(chrom),
                             color = color,
                             sample_name = unlist(strsplit(names(dat[i]), ".", fixed = TRUE))[[1]])
        }
        dev.off()
}
pdf("../Plots/scale_bar.pdf", height = 2, width = 5)
image(matrix(seq(100)), col = color, main = "scale")
dev.off()
```

